# NOTE: Deploy with: docker-compose up -d --build
version: '3.1'
services:
  trashloc:
    build: .
    image: test:latest
    container_name: trashloc
    ports:
      - 80:80
    environment:
      - DEBUG=True